# --------------------------------------------------------------------------------------------------------------------------------------------------
# Getting Base image (ubuntu 20.04)
# --------------------------------------------------------------------------------------------------------------------------------------------------
FROM ghcr.io/ucsd-ecemae-148/donkeycontainer:utils

####### CREATE VIRTUAL ENVIRONMENTS #######
RUN echo "alias python=python3" >> ~/.bashrc
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv "${VIRTUAL_ENV}/ros" --system-site-packages

# --------------------------------------------------------------------------------------------------------------------------------------------------
# Install ROS2 Foxy 
# --------------------------------------------------------------------------------------------------------------------------------------------------
RUN apt update &&\
    apt install software-properties-common -y && \
    add-apt-repository universe && \
    apt update && sudo apt install curl -y && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

# --------------------------------------------------------------------------------------------------------------------------------------------------
# Setting environment variable
# --------------------------------------------------------------------------------------------------------------------------------------------------
ENV ROS2_DISTRO foxy

####################################################################################################################################################
# Install required packages/dependencies for ros2
####################################################################################################################################################
#
#

WORKDIR /

# --------------------------------------------------------------------------------------------------------------------------------------------------
# intel debian packages
# --------------------------------------------------------------------------------------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl-dev \
    libusb-1.0-0-dev \
    pkg-config \
    libgtk-3-dev \
    libglfw3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libssl-dev \
    libusb-1.0-0-dev \
    pkg-config \
    libgtk-3-dev \
    libglfw3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    build-essential \
    libgtk-3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    build-essential \
    libgtk-3-dev


# --------------------------------------------------------------------------------------------------------------------------------------------------
# install ros2 packages
# --------------------------------------------------------------------------------------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-foxy-desktop=0.9.2-1* \
    ros-foxy-message-filters \
    ros-foxy-image-transport \
    ros-foxy-teleop-twist-joy \
    ros-foxy-joy \
    ros-foxy-joy-teleop \
    ros-foxy-rviz-default-plugins \
    ros-foxy-rviz-rendering \
    ros-foxy-ros2bag \
    ros-foxy-rosbag2-converter-default-plugins \
    ros-foxy-rosbag2-storage-default-plugins \
    ros-foxy-robot-localization \
    ros-foxy-slam-toolbox \
    ros-foxy-ackermann-msgs \
    ros-foxy-serial-driver \
    ros-foxy-depthai-ros \
    ros-foxy-pcl-ros \
    && rm -rf /var/lib/apt/lists/*
# --------------------------------------------------------------------------------------------------------------------------------------------------
# install useful packages

# Not sure if these are needed...
#    ros-foxy-rviz2 \
#    ros-foxy-rviz-common \
#    ros-foxy-realsense2-camera-description \

# --------------------------------------------------------------------------------------------------------------------------------------------------
# install useful packages
# --------------------------------------------------------------------------------------------------------------------------------------------------
WORKDIR /
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    python3-argcomplete \
    nano \
    iputils-ping \
    x11-apps \
    nautilus \
    vim \
    tmux \
    tmuxp \
    firefox \
    git-all \
    cheese \
    jstest-gtk \
    joystick \
    gedit \
    gedit-plugin-multi-edit \
    gedit-plugins \
    python3-tk \
    python3-rosdep \
    python3-vcstool \
    ros-dev-tools


RUN apt-get update && \
    source ${VIRTUAL_ENV}/ros/bin/activate && \
    pip3 install \
    pandas \
    control

RUN export ROS_DISTRO=foxy
RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
